/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWashingMachineRepairRouteImport } from './routes/services.washing-machine-repair'
import { Route as ServicesRefrigeratorRepairRouteImport } from './routes/services.refrigerator-repair'
import { Route as ServicesAcRepairRouteImport } from './routes/services.ac-repair'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWashingMachineRepairRoute =
  ServicesWashingMachineRepairRouteImport.update({
    id: '/washing-machine-repair',
    path: '/washing-machine-repair',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesRefrigeratorRepairRoute =
  ServicesRefrigeratorRepairRouteImport.update({
    id: '/refrigerator-repair',
    path: '/refrigerator-repair',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesAcRepairRoute = ServicesAcRepairRouteImport.update({
  id: '/ac-repair',
  path: '/ac-repair',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/ac-repair': typeof ServicesAcRepairRoute
  '/services/refrigerator-repair': typeof ServicesRefrigeratorRepairRoute
  '/services/washing-machine-repair': typeof ServicesWashingMachineRepairRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/ac-repair': typeof ServicesAcRepairRoute
  '/services/refrigerator-repair': typeof ServicesRefrigeratorRepairRoute
  '/services/washing-machine-repair': typeof ServicesWashingMachineRepairRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/ac-repair': typeof ServicesAcRepairRoute
  '/services/refrigerator-repair': typeof ServicesRefrigeratorRepairRoute
  '/services/washing-machine-repair': typeof ServicesWashingMachineRepairRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/services/ac-repair'
    | '/services/refrigerator-repair'
    | '/services/washing-machine-repair'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/services/ac-repair'
    | '/services/refrigerator-repair'
    | '/services/washing-machine-repair'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/services/ac-repair'
    | '/services/refrigerator-repair'
    | '/services/washing-machine-repair'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/washing-machine-repair': {
      id: '/services/washing-machine-repair'
      path: '/washing-machine-repair'
      fullPath: '/services/washing-machine-repair'
      preLoaderRoute: typeof ServicesWashingMachineRepairRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/refrigerator-repair': {
      id: '/services/refrigerator-repair'
      path: '/refrigerator-repair'
      fullPath: '/services/refrigerator-repair'
      preLoaderRoute: typeof ServicesRefrigeratorRepairRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ac-repair': {
      id: '/services/ac-repair'
      path: '/ac-repair'
      fullPath: '/services/ac-repair'
      preLoaderRoute: typeof ServicesAcRepairRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAcRepairRoute: typeof ServicesAcRepairRoute
  ServicesRefrigeratorRepairRoute: typeof ServicesRefrigeratorRepairRoute
  ServicesWashingMachineRepairRoute: typeof ServicesWashingMachineRepairRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAcRepairRoute: ServicesAcRepairRoute,
  ServicesRefrigeratorRepairRoute: ServicesRefrigeratorRepairRoute,
  ServicesWashingMachineRepairRoute: ServicesWashingMachineRepairRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
